{{- if .Values.postgresql-keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgresql-keycloak
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "postgresql-keycloak.labels" . | nindent 4 }}
    app: postgresql-keycloak
spec:
  type: {{ .Values.postgresql-keycloak.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.postgresql-keycloak.service.port }}
    targetPort: postgresql
    protocol: TCP
  selector:
    app: postgresql-keycloak
  clusterIP: None  # Headless service for StatefulSet
{{- end }}
