apiVersion: v2
name: rhdemo
description: RHDemo Application - Helm Chart pour d√©ploiement Kubernetes
type: application
version: 1.0.0
appVersion: "1.1.0-SNAPSHOT"
keywords:
  - rhdemo
  - spring-boot
  - keycloak
  - postgresql
home: https://github.com/votre-org/rhDemo
sources:
  - https://github.com/votre-org/rhDemo
maintainers:
  - name: RHDemo Team
